exclude:
  - node_modules
  - script

sass:
  style: :compressed

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/pages-themes/primer"
  
title: Jekyll Theme Primer
description: Primer is a Jekyll theme for GitHub Pages

remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one